# Generated by Django 4.1.2 on 2022-10-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideaapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
